apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  identity-database-sa-password: aWRlbnRpdHlEYXRhYmFzZVBhc3N3b3JkMTIhQA==
  dealers-database-sa-password: ZGVhbGVyc0RhdGFiYXNlUGFzc3dvcmQxMiFA
  statistics-database-sa-password: c3RhdGlzdGljc0RhdGFiYXNlUGFzc3dvcmQxMiFA
  security-token-secret: UzBNMyBNNEcxQyBVTjFDMFJOUyBHM04zUjRUM0QgVEgxUyBTM0NSM1QK
  admin-password: YWRtaW5wYXNzMTIh
  identity-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbElkZW50aXR5RGF0YWJhc2U7VXNlciBJZD1zYTtQYXNzd29yZD1pZGVudGl0eURhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVlO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1UcnVlOw==
  event-bus-user: cmFiYml0bXF1c2Vy
  event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==