apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: identity-service-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
      - name: IdentitySettings__AdminPassword
        valueFrom:
          secretKeyRef:
            name: environment-secrets
            key: admin-password
    volumeMounts:
        - name: identity-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
  volumes:
    - name: identity-service-data
      persistentVolumeClaim:
      claimName: identity-service-data